#SVM

## Base de dados Titanic

In [ ]:
import seaborn as sns

tit = sns.load_dataset('titanic')
tit.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

## Filtragem dos dados

In [ ]:
import pandas as pd
import numpy as np

tit = sns.load_dataset('titanic')

# Conversão dos dados de 'alone' para números (0 e 1)
tit['alone'] = tit['alone'].astype(int)

# Conversão dos dados de 'who' para números (0, 1 e 2)
tit['who'] = tit['who'].map({'man': 0, 'woman': 1, 'child': 2})

# Remoção das linhas com valores 'NaN' na coluna 'age'
tit.dropna(subset=['age'], inplace=True)

X = tit[['age', 'sibsp', 'parch', 'pclass', 'who', 'alone']].values
y = tit[['survived']].values

print(X.shape)
print(y.shape)

tit.head(10)

(714, 6)
(714, 1)


survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0          0       3    male  22.0      1      0   7.2500        S   Third   
1          1       1  female  38.0      1      0  71.2833        C   First   
2          1       3  female  26.0      0      0   7.9250        S   Third   
3          1       1  female  35.0      1      0  53.1000        S   First   
4          0       3    male  35.0      0      0   8.0500        S   Third   
6          0       1    male  54.0      0      0  51.8625        S   First   
7          0       3    male   2.0      3      1  21.0750        S   Third   
8          1       3  female  27.0      0      2  11.1333        S   Third   
9          1       2  female  14.0      1      0  30.0708        C  Second   
10         1       3  female   4.0      1      1  16.7000        S   Third   

    who  adult_male deck  embark_town alive  alone  
0     0        True  NaN  Southampton    no      0  
1     1       False    C    Cherbourg   yes      0  
2     1       False  NaN  Southampton   yes      1  
3     1       False    C  Southampton   yes      0  
4     0        True  NaN  Southampton    no      1  
6     0        True    E  Southampton    no      1  
7     2       False  NaN  Southampton    no      0  
8     1       False  NaN  Southampton   yes      0  
9     2       False  NaN    Cherbourg   yes      0  
10    2       False    G  Southampton   yes      0

In [ ]:
print(X[:5])

[[22.  1.  0.  3.  0.  0.]
 [38.  1.  0.  1.  1.  0.]
 [26.  0.  0.  3.  1.  1.]
 [35.  1.  0.  1.  1.  0.]
 [35.  0.  0.  3.  0.  1.]]


In [ ]:
print(y[:5])

[[0]
 [1]
 [1]
 [1]
 [0]]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

print("Tamanho de X_train:", X_train.shape)
print("Tamanho de X_test:", X_test.shape)
print("Tamanho de y_train:", y_train.shape)
print("Tamanho de y_test:", y_test.shape)


Tamanho de X_train: (535, 6)
Tamanho de X_test: (179, 6)
Tamanho de y_train: (535, 1)
Tamanho de y_test: (179, 1)


## Treinamento com SVM com kernel linear

In [ ]:
from sklearn.svm import SVC

classifier_svm = SVC(kernel='linear', random_state=0)

classifier_svm.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', random_state=0)

## Medição da acurácia e matriz de confusão

In [ ]:
# prompt: Faça a avaliação do modelo calculando a acurácia e a matriz de confusão

from sklearn.metrics import confusion_matrix, accuracy_score

# Predizendo as classes dos dados de teste
y_pred = classifier_svm.predict(X_test)

# Calculando a acurácia do modelo
accuracy = accuracy_score(y_test, y_pred)
print("Acurácia do modelo:", accuracy)

# Calculando a matriz de confusão do modelo
conf_matrix = confusion_matrix(y_test, y_pred)
print("Matriz de confusão:")
print(conf_matrix)

Acurácia do modelo: 0.7877094972067039
Matriz de confusão:
[[87 16]
 [22 54]]
